// <auto-generated />
namespace EducationSurveyAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init2db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init2db));
        
        string IMigrationMetadata.Id
        {
            get { return "202205270803536_init2db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
